config/routes.rb
Rails.application.routes.draw do

  direct :rails_blob do |blob|
    "/rails/active_storage/blobs/#{blob.signed_id}/#{blob.filename}"
  end

  get 'search', to: 'products#search', as: 'search_products'

  # post '/stripe/webhook', to: 'payments#webhook'

    post 'payments/webhook', to: 'payments#webhook'
  
  

  devise_for :users

  resources :users do
    patch 'users/:id/edit', to: 'users#edit'
  end

  root to: "products#index"

  get 'product_register', to:'products#new'
  post 'product_register' , to:'products#create'
  get 'product', to:'products#index'
  get 'product/:id', to:'products#show', as: 'products'
  get 'sub_categories', to: 'products#sub_categories'

 

  resources :cart_items
  resources :wishlist_items, only: [:index,:destroy,:create]
  resources :carts, only:[:index,:destroy,:create]

  resources :products do
    resources :reviews 
  end

  resources :users do
    resources :addresses, only: [:index, :new, :create]
  end

  resources :carts do
    member do
      get 'invoice'
    end
  end
  
  resources :payments

  get 'ordered_items', to: 'carts#ordered_items', as: 'ordered_items'


  resources :payments, only: [:new, :create] do
    collection do
      post :create
      get :success
      get :cancel
    end
  end
end

app/views/shared/_category_dropdown.html.erb
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    <% if params[:category].present? %>
      <%= params[:category].capitalize %>  <!-- Display the selected category -->
    <% else %>
      Select Category  <!-- Default text if no category is selected -->
    <% end %>
  </button>
  
  <ul class="dropdown-menu" aria-labelledby="dropdown-toggle">
    <% if @categories.present? %>
      <% @categories.each do |category| %>
        <li>
          <%= link_to category, product_path(query: params[:query], category: category), class: "dropdown-item" %>
        </li>
      <% end %>
    <% else %>
      <li>No categories available</li>
    <% end %>
  </ul>
</div>

app/views/shared/_flash.html.erb
<% [:notice, :alert, :error].each do |type| %>
    <% if flash[type] %>
      <div id=`flash-#{type}` class="alert <%= type == :notice ? 'alert-success' : (type == :alert ? 'alert-warning' : 'alert-danger') %>" role="alert" >
        <%= flash[type] %>
      </div>
    <% end %>
  <% end %>


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
  $('#flash').fadeOut();
  }, 2000);
})
</script>

app/views/shared/_modal.html.erb
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="<%= modal_id %>Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="<%= modal_id %>Label"><%= modal_title %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      

      <div class="modal-footer">
        <%= form_with url: payments_path(@cart), method: :post, local: true, id: "purchase-form" do %>
          <% if @user.addresses.length > 0 %>
        <div class="modal-body">
          <%= yield %>
          <h5>Select an Address:</h5>
          <div id="address-selection">
            <% @user.addresses.each do |address| %>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="selected_address" id="address_<%= address.id %>" value="<%= address.id %>">
                <label class="form-check-label" for="address_<%= address.id %>">
                  <%= address.content %>
                </label>
              </div>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="modal-body">
          <p>You have no addresses. <%= link_to "Add your address", edit_user_registration_path %></p>
        </div>
      <% end %>

          <%= hidden_field_tag :cart_id, @cart.id %>
          <div id="hidden-quantities"></div> 
         
          <p>Total: <strong id="modal-subtotal-amount"><%= calculate_subtotal(@cart) %></strong></p>
          
          <button type="submit" class="btn btn-text-size btn-color" data-turbo="false">BUY NOW</button>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg py-2 fixed-top " style="background-color:#F8F0E3">


  <div class="container-fluid">
    <a class="navbar-brand text-color" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item d-flex align-items-center">
          <%= button_to "Home",
                        product_path,
                        method: :get,
                        class: "btn btn-link outline-none text-decoration-none text-color",
                        data: { turbolinks: false } %>
        </li>
      </ul>

       <%= render "shared/search" %>

      <ul class="d-flex align-items-center justify-content-evenly w-25" style="list-style: none; padding: 0; margin: 0;">
  <li class="nav-item text-decoration-none">
    <%= button_to raw("<i class='bi bi-heart'></i>"),
                  wishlist_items_path,
                  method: :get,
                  class: "btn btn-link outline-none fs-4 text-black",
                  data: { turbolinks: false },
                  disabled: !user_signed_in? %>
  </li>
  <li class="nav-item">
    <%= button_to raw("<i class='bi bi-cart'></i>"),
                  carts_path,
                  method: :get,
                  class: "btn btn-link outline-none fs-4 text-black",
                  data: { turbolinks: false },
                  disabled: !user_signed_in? %>
  </li>

    <%= render "shared/category_dropdown" %>
  
  <li>
    <% if user_signed_in? %>
      <%= button_to raw("<i class='bi bi-person'></i>"),
                    edit_user_registration_path,
                    method: :get,
                    class: "btn btn-link outline-none fs-4 text-black",
                    data: { turbolinks: false } %>
    <% else %> 
      <%= button_to raw("<i class='bi bi-person'></i>"),
                    new_user_session_path,
                    method: :get,
                    class: "btn btn-link outline-none fs-4 text-black",
                    data: { turbolinks: false } %>
    <% end %>
  </li>
</ul>
    </div>
  </div>
</nav>

app/views/shared/_reply_modal.erb
<div class="modal fade" id="replyModal" tabindex="-1" aria-labelledby="replyModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="replyModalLabel">Reply to Review</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <%= form_with(model: [@product, Review.new], local: true) do |form| %>
        <div class="form-group">
          <%= form.label :content %>
          <%= form.text_area :content, required: true %>
        </div>
        <%= form.hidden_field :parent_id, value: @parent_id %> 
        <p>Parent ID: <%= @parent_id %></p>
        <%= form.submit 'Submit Reply' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= form_with url: product_path, method: :get, local: true do |form| %>
    <div class="form-group rounded-pill  d-flex align-items-center px-2 bg-white">
      <%= form.text_field :query, class: 'form-control rounded-pill border-0 w-100 outline-none',  value: params[:query].presence , placeholder: '' %>
      <i class="bi bi-search"></i>
    </div>
  
<% end %>