config/routes.rb
Rails.application.routes.draw do

  direct :rails_blob do |blob|
    "/rails/active_storage/blobs/#{blob.signed_id}/#{blob.filename}"
  end

  get 'search', to: 'products#search', as: 'search_products'

  # post '/stripe/webhook', to: 'payments#webhook'

    post 'payments/webhook', to: 'payments#webhook'
  
  

  devise_for :users

  resources :users do
    patch 'users/:id/edit', to: 'users#edit'
  end

  root to: "products#index"

  get 'product_register', to:'products#new'
  post 'product_register' , to:'products#create'
  get 'product', to:'products#index'
  get 'product/:id', to:'products#show', as: 'products'
  get 'sub_categories', to: 'products#sub_categories'

 

  resources :cart_items
  resources :wishlist_items, only: [:index,:destroy,:create]
  resources :carts, only:[:index,:destroy,:create]

  resources :products do
    resources :reviews 
  end

  resources :users do
    resources :addresses, only: [:index, :new, :create]
  end

  resources :carts do
    member do
      get 'invoice'
    end
  end
  
  resources :payments

  get 'ordered_items', to: 'carts#ordered_items', as: 'ordered_items'


  resources :payments, only: [:new, :create] do
    collection do
      post :create
      get :success
      get :cancel
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items, dependent: :destroy
  belongs_to :address, optional: true

  scope :ordered, -> { order(created_at: :desc) }
  scope :items, ->(data){ where(ordered: data)}

  validates :user, presence: true

  def add_or_update_item(product_id, quantity)
    cart_item = cart_items.find_by(product_id: product_id)

    if cart_item
      cart_item.update_quantity(quantity)
    else
      cart_items.create(product_id: product_id, quantity: quantity, total: calculate_total(product_id, quantity))
    end

    update_cart_subtotal
    cart_item
  end

  def calculate_total(product_id, quantity)
    product = products.find(product_id)
    product.price * quantity
  end

  def update_cart_subtotal
    subtotal = cart_items.sum(:total)
    update(subtotal: subtotal)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:index, :invoice]
  before_action :set_carts, only: [:index, :ordered_items, :create, :invoice]

  def index
    @user=current_user
    @cart = @carts.items(false).ordered.first
  end

  def show
  end

  def ordered_items
    @ordered_carts = @carts.items(true).ordered.page(params[:page])
  end

  def create
    product_id = params[:product_id] || params[:cartitem_id]
    quantity = params[:quantity].to_i > 0 ? params[:quantity].to_i : 1
    cart = @carts.find_or_create_by(ordered: false)

    cart_item = cart.add_or_update_item(product_id, quantity)

    remove_from_wishlist if params[:cartitem_id]

    flash[:notice] = "Product added to cart." 
    redirect_to carts_path(cart_item)
  end

  def invoice
    @cart = @carts.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Carts: #{@cart.id}",
               template: "carts/invoice",
               formats: [:html],
               disposition: :inline,
               layout: "pdf"
      end
    end
  end

  private

  def remove_from_wishlist
    id = params[:cartitem_id]
    wishlist_item = current_user.wishlist_items.find_by(product_id: id)
    wishlist_item.destroy if wishlist_item
  end

  def set_cart
    @cart = current_user.carts.find_or_create_by(ordered: false)
  end

  def set_carts
    @carts = current_user.carts
  end

  def cart_params
    params.require(:cart).permit(:subtotal, cart_items_attributes: [:id, :quantity])
  end
end

app/views/carts/_cart_item.html.erb
<% cart_items.each do |cart| %>
<div class="col-md-3">
    <div class="card mb-4 shadow-sm">
        <div class="d-flex justify-content-end">
            <%= button_to raw("<i class='bi bi-x-lg'></i>"), cart_item_path(cart.id), method: :delete, class: "outline-none p-2 fs-5",
                                                                                      data: { turbo: false } %>
        </div>
             
        <div>
            <% if cart.product.image.attached? %>
              <img src="<%= url_for(cart.product.image) %>" class="image-size card-img-top" alt="<%= cart.product.name %>">
            <% else %>
              <%= image_tag "grey-pant.webp", class: "image-size card-img-top", alt: "Description of the image" %>
            <% end %>
        </div>
            
        <div class="card-body">
            <h5 class="card-title"><%= cart.product.name %></h5>
            <p class="card-text">
                Total Price: <span id="total-price-<%= cart.id %>"><%= cart.product.price * cart.quantity %></span>   
            </p>
            <div class="d-flex align-items-center">
                <button type="button" class="btn btn-decrease btn-text-size btn-color" data-cart-item-id="<%= cart.id %>" data-price="<%= cart.product.price %>">-</button>
                <span id="quantity-<%= cart.id %>" class="mx-2"><%= cart.quantity %></span>
                <button type="button" id="btn-increase" class="btn btn-increase btn-text-size btn-color" data-cart-item-id="<%= cart.id %>" data-price="<%= cart.product.price %>">+</button>
            </div>
        </div>
        
    </div>
</div>
<% end %>

app/views/carts/_ordered_item.html.erb
<% cart_items.includes(:product).each do |cart_item| %>
  <div class="col-md-3">
    <div class="card mb-4 shadow-sm col-12 mb-3">
      <% if cart_item.product.image.attached? %> 
        <img src="<%= url_for(cart_item.product.image) %>" class="order-image-size card-img-top" alt="<%= cart_item.product.name %>">
      <% else %>
        <%= image_tag "grey-pant.webp", class: "order-image-size card-img-top", alt: "Description of the image" %>
      <% end %>

      <div class="card-body">
        <h5 class="card-title"><%= cart_item.product.name %></h5>
        <p class="card-text">Quantity: <%= cart_item.quantity %></p>
        <p class="card-text">Total Price: <%= format_price(cart_item.product.price * cart_item.quantity) %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/carts/index.html.erb
<% if @cart && @cart.cart_items.any? %> 
<h1>Cart Items</h1>
<div class="container mt-1">
  <div class="row">
    <%= render "cart_item", cart_items: @cart.cart_items %> 
  </div>

  <div class="mt-3">
    <p>
      Total: 
      <strong id="subtotal-amount">
        <%= calculate_subtotal(@cart) %>
      </strong>
    </p>
    <br>
    <strong>Total Quantity: </strong>
    <span id="total-quantity"><%= @cart.cart_items.sum(:quantity) %></span>
  </div>

  <div class="my-3">
    <button type="button" class="btn btn-text-size btn-color" data-bs-toggle="modal" data-bs-target="#purchaseModal">
      PURCHASE
    </button>
  </div>

  <%= render "shared/modal",
             modal_id: "purchaseModal",
             modal_title: "Confirm Purchase",
             modal_footer: button_to("BUY NOW", payments_path(@cart), method: :post, class: "btn btn-text-size btn-color",
                                                                      data: { address_id: "selected_address" }) do %>
  <% end %>

    


</div>

<% else %> 
<h1>Cart empty!</h1>
<% end %>

app/views/carts/invoice.html.erb
<h1>Invoice ##<%= @cart.id %></h1>
<p>Date: <%= @cart.created_at.strftime("%Y-%m-%d") %></p>
<p>Customer: <%= @cart.user.name %></p>

<h2>Order Details</h2>
<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.cart_items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %></td>
        <td><%= format_price(item.total) %>

      </tr>
    <% end %>
  </tbody>
</table>

<h2>Total:  <%= format_price(@cart.subtotal) %></h2>

app/views/carts/ordered_items.html.erb
<h1 class="text-center">Ordered Items</h1>

<% if @ordered_carts.any? %>
<div class="container mt-1">
  <div class="row">
    <% @ordered_carts.each do |ordered_cart| %>
      
      <div class="border border-black p-3 rounded m-3">
        <h3 class="py-2">Order ID: <%= ordered_cart.id %></h3>

          <%= render "ordered_item", cart_items: ordered_cart.cart_items %>
          
        <div class="row">
        </div>
        <h3 class="">Subtotal: <%= format_price(ordered_cart.subtotal) %></h3>
        <%= link_to "Download Invoice", invoice_cart_path(ordered_cart, format: :pdf), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="p-3 d-flex justify-content-center fs-5 pagination-container">
    <div class="bg-white">
      <%= link_to_previous_page @ordered_carts, "<i class='bi bi-chevron-left'></i>".html_safe, class: "pagination-link fs-5" %>
      <span><%= @ordered_carts.current_page %> / <%= @ordered_carts.total_pages %></span>
      <%= link_to_next_page @ordered_carts, "<i class='bi bi-chevron-right'></i>".html_safe, class: "pagination-link fs-5" %>
    </div>
  </div>
</div>
  
<% else %>
  <h3>No previous orders!</h3>
<% end %>