config/routes.rb
Rails.application.routes.draw do

  direct :rails_blob do |blob|
    "/rails/active_storage/blobs/#{blob.signed_id}/#{blob.filename}"
  end

  get 'search', to: 'products#search', as: 'search_products'

  # post '/stripe/webhook', to: 'payments#webhook'

    post 'payments/webhook', to: 'payments#webhook'
  
  

  devise_for :users

  resources :users do
    patch 'users/:id/edit', to: 'users#edit'
  end

  root to: "products#index"

  get 'product_register', to:'products#new'
  post 'product_register' , to:'products#create'
  get 'product', to:'products#index'
  get 'product/:id', to:'products#show', as: 'products'
  get 'sub_categories', to: 'products#sub_categories'

 

  resources :cart_items
  resources :wishlist_items, only: [:index,:destroy,:create]
  resources :carts, only:[:index,:destroy,:create]

  resources :products do
    resources :reviews 
  end

  resources :users do
    resources :addresses, only: [:index, :new, :create]
  end

  resources :carts do
    member do
      get 'invoice'
    end
  end
  
  resources :payments

  get 'ordered_items', to: 'carts#ordered_items', as: 'ordered_items'


  resources :payments, only: [:new, :create] do
    collection do
      post :create
      get :success
      get :cancel
    end
  end
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :products 

  def self.add_or_remove_from_wishlist(user, product_id)
    item = user.wishlist_items.find_or_initialize_by(product_id: product_id)

    if item.new_record?
      item.save
    else
      item.destroy
    end
    item
  end

  def remove_item(id)
    item = find_by(id)
    item&.destroy 
    item
  end
 

end

app/controllers/wishlist_items_controller.rb
class WishlistItemsController < ApplicationController
  before_action :set_wishlist
  def index
    @wishlist_items = @wishlist.order(created_at: :desc)
  end

  def create
    product_id = params[:product_id]
    @wish_list_item = WishlistItem.add_or_remove_from_wishlist(current_user,product_id)

    if @wish_list_item.persisted?
      flash[:notice] = "Added to wishlist!"
      redirect_to request.referer
    else
      flash[:notice] = "Removed from wishlist!"
      redirect_to request.referer
    end
  end

  def destroy
    if WishlistItem.remove_item(params[:id])
      flash[:notice] = "Item removed from wishlist!"
    else
      flash[:alert] = "Error: Item not found or you do not have permission to remove it."
    end
    redirect_to wishlist_items_path
  end

  private 
  def set_wishlist
    @wishlist= current_user.wishlist_items
  end
end

app/views/wishlist_items/index.html.erb
<% if @wishlist_items.any? %>
<h1 class="text-center">Wishlist Items</h1>
  <div class="container mt-1">
    <div class="row">
      <% @wishlist_items.each do |wishlist_item| %>
        <div class="col-md-3">
        <div class="card mb-4 shadow-sm">
       
        <div class="card">
        <div class="d-flex justify-content-end ">
          
            <%= button_to raw("<i class='bi bi-x-lg'></i>"), wishlist_item_path(wishlist_item.id), method: :delete, class: "outline-none p-2  fs-5",
                                                                                                   data: { turbolinks: false } %> 

        </div>

            <% product = wishlist_item.product %> 
            <div class="p-2">
            <% if product.image.attached? %>
              <img src="<%= url_for(product.image) %>" class="image-size card-img-top" alt="<%= product.name %>">
            <% else %>
              <%= image_tag "grey-pant.webp", class: "image-size card-img-top", alt: "Description of the image" %>
            <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= product.name %></h5>
              <p class="card-text">Price: <%= format_price(product.price) %></p>
            
                <%= button_to "ADD TO CART", carts_path(cartitem_id: product.id), method: :post, class: "btn btn-color btn-text-size" %>
            </div>
          </div>
        </div>
        
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <h3>No items in your wishlist!</h3>
<% end %>