config/routes.rb
Rails.application.routes.draw do

  direct :rails_blob do |blob|
    "/rails/active_storage/blobs/#{blob.signed_id}/#{blob.filename}"
  end

  get 'search', to: 'products#search', as: 'search_products'

  # post '/stripe/webhook', to: 'payments#webhook'

    post 'payments/webhook', to: 'payments#webhook'
  
  

  devise_for :users

  resources :users do
    patch 'users/:id/edit', to: 'users#edit'
  end

  root to: "products#index"

  get 'product_register', to:'products#new'
  post 'product_register' , to:'products#create'
  get 'product', to:'products#index'
  get 'product/:id', to:'products#show', as: 'products'
  get 'sub_categories', to: 'products#sub_categories'

 

  resources :cart_items
  resources :wishlist_items, only: [:index,:destroy,:create]
  resources :carts, only:[:index,:destroy,:create]

  resources :products do
    resources :reviews 
  end

  resources :users do
    resources :addresses, only: [:index, :new, :create]
  end

  resources :carts do
    member do
      get 'invoice'
    end
  end
  
  resources :payments

  get 'ordered_items', to: 'carts#ordered_items', as: 'ordered_items'


  resources :payments, only: [:new, :create] do
    collection do
      post :create
      get :success
      get :cancel
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :sub_category

  has_many :wishlist_items
  has_many :cart_items
  has_many :reviews

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  scope :order_price_by_asc, -> { order(price: :asc) }

  scope :category, ->{joins(sub_category: :category)
  .where(sub_categories: { category_id: category.id })
  .includes(:sub_category)}
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_wishlist_items, only: [:index, :show]

  def index
    @products = Product.all

    if params[:query].present?
      search_item
    end

    if params[:price_range].present?
      select_price_range
    end

    if params[:category].present?
      select_category
    end

    @price_ranges = [
      { label: "Under ₹500", min: 0, max: 500 },
      { label: "₹500 - ₹1000", min: 500, max: 1000 },
      { label: "₹1000 - ₹5000", min: 1000, max: 5000 },
      { label: "₹5000 - ₹10,000", min: 5000, max: 10000 },
      { label: "Over ₹10,000", min: 10000, max: 100000 },
    ]

    @categories = Category.pluck(:category_name)
  end

  def new
    @product = Product.new
    @categories = Category.all
    @sub_categories = []
  end

  def create
    @product = Product.new(product_params)
    @product=Product
    if @product.save
      redirect_to product_path, notice: "Product registered!"
    else
      flash[:error] = @product.errors.full_messages
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def sub_categories
    if params[:category_id]
      @sub_categories = SubCategory.where(category_id: params[:category_id])
      render json: @sub_categories.select(:id, :subcategory_name)
    else
      render json: []
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :image, :sub_category_id)
  end

  def set_wishlist_items
    @wishlist_items = user_signed_in? ? current_user.wishlist_items.pluck(:product_id) : []
  end

  def search_item
    query = params[:query].downcase.strip
    @products = @products.joins(sub_category: :category)
                         .where("LOWER(products.name) LIKE :query OR LOWER(sub_categories.subcategory_name) LIKE :query 
                                OR LOWER(categories.category_name) LIKE :query", query: "%#{query}%")
                         .distinct
  end

  def  select_price_range
    price_min, price_max = params[:price_range].split(",").map(&:to_i)
    @products = 
      if price_max == 100000
        @products.where("price >= ?", price_min)
      else
        @products.where(price: price_min..price_max)
      end
  end

  def select_category
    category = Category.find_by(category_name: params[:category])
    @products = []
    if category
      @products = Product.joins(sub_category: :category)
                        .where(sub_categories: { category_id: category.id })
                        .includes(:sub_category)   
    end
  end


end

app/helpers/products_helper.rb
module ProductsHelper
  def format_price(price)
    number_to_currency(price, unit: "₹")
  end

  def calculate_subtotal(cart)
    number_to_currency(cart.cart_items.sum { |item| item.product.price * item.quantity },unit: "₹")
  end

end

app/views/products/_price_range.html.erb
<% if params[:query].present? %>
    <p>Showing results for: "<%= params[:query] %>"</p>

    <div class="price-range-footer p-3 mt-4 bg-light">
      <h5>Filter by Price Range</h5>
      <form method="get" action="<%= request.path %>" id="price-range-form">
        <input type="hidden" name="query" value="<%= params[:query] %>" />

        <select name="price_range" id="price-range-select" class="form-select" onchange="this.form.submit()">
          <option value="">Select Price Range</option>
          <% @price_ranges.each do |range| %>
            <option value="<%= range[:min] %>,<%= range[:max] %>" <%= "selected" if params[:price_range] == "#{range[:min]},#{range[:max]}" %> >
              <%= range[:label] %>
            </option>
          <% end %>
        </select>
      </form>
    </div>
  <% end %>

app/views/products/_product_details.html.erb
<div class="col-md-6 mx-auto">
    <h1 class="mb-4 text-color"><%= @product.name %></h1>
    <p class="h4 text-color ">Price: <%= format_price(@product.price) %></p>
    <p><%= @product.description %></p>

    <div class="d-flex justify-content-between align-items-center">
        <% if user_signed_in? %>
            <%= button_to "ADD TO CART", carts_path(product_id: @product.id), method: :post, class: "btn btn-color text-grey fs-7" %>
        <% else %>
            <%= link_to "ADD TO CART", new_user_session_path, class: "btn btn-color text-grey fs-7" %>
        <% end %>

        <%= button_to raw("<i class='bi bi-heart" + (@wishlist_items.include?(@product.id) ? "-fill" : "") + "'></i>"),
                      wishlist_items_path(product_id: @product.id),
                      method: :post,
                      class: "outline-none fs-4",
                      data: { turbolinks: false },
                      disabled: !user_signed_in? %>

        <%= button_to raw("<i class='bi bi-chat'></i>"),
                      product_reviews_path(product_id: @product.id),
                      method: :get,
                      class: "outline-none text-grey fs-4",
                      disabled: !user_signed_in? %>
    </div>
</div>

app/views/products/index.html.erb
<div class="container mt-1 ">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3 ">
        <div class="card mb-4 shadow-sm">
          <div class='p-2'>
            <% if product.image.attached? %>
              <img src="<%= url_for(product.image) %>" class="image-size card-img-top " alt="<%= product.name %>">
            <% else %>
              <%= image_tag "grey-pant.webp", class: "image-size card-img-top", alt: "Description of the image" %>
            <% end %>
          </div>
          <div class="card-body"> 
            <h5 class="card-title ">
              <%= link_to product.name, products_path(product), class: "text-color" %>
            </h5>

            <p class="card-text text-color">
              Price: <%= format_price(product.price) %>
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="d-flex justify-content-between align-items-center w-100">
                <%= button_to raw("<i class='bi bi-heart" + (@wishlist_items.include?(product.id) ? "-fill" : "") + "'></i>"),
                              wishlist_items_path(product_id: product.id),
                              method: :post,
                              class: "outline-none fs-5",
                              data: { turbolinks: false },
                              disabled: !user_signed_in? %>
              </div>
            </div>
          </div>
     
        </div>
      </div>
    <% end %>
  </div>
  <%= render "price_range" %>
</div>

app/views/products/new.html.erb
<%= render "devise/shared/error_messages", resource: @product %>
<div class='container'>
  <div class='row justify-content-center'>
    <div class='col-5'>
      <div class='mt-3'>
        <h1>Register Product</h1>
      </div>

      <%= form_with model: @product, url: product_register_path, local: true, html: { multipart: true } do |form| %>

        <div class='form-group row mt-3'>
          <%= form.label :name, "Name of product" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class='form-group row mt-3'>
          <%= form.label :price, "Enter price" %>
          <%= form.text_field :price, class: "form-control" %>
        </div>

        <div class='form-group row mt-3'>
          <%= form.label :image, "Upload image" %>
          <%= form.file_field :image, class: "form-control" %>
        </div>

        <div class='form-group row mt-3'>
          <%= form.label :category_id, "Select Category" %>
          <%= form.select :category_id, @categories.map { |category| [category.category_name, category.id] }, { prompt: "Choose a category" }, { class: "form-control", id: "category-select" } %>
        </div>

        <div class='form-group row mt-3'>
        <%= form.label :subcategory_id, "Select Subcategory" %>
        <%= form.select :sub_category_id, [], { prompt: "Choose a subcategory" }, { class: "form-control", id: "sub-category-select" } %>
        </div>

        <div class='form-group row mt-3'>
          <%= form.submit "Register Product", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container mt-1 ">
  <div class="row d-block mx-auto">
    <div class="col-md-6 mx-auto border border-black rounded">
      <div class="d-flex justify-content-start p-0 m-0">
        <%= button_to raw("<i class='bi bi-arrow-left fs-4 outline-none'></i>"),
                      product_path,
                      method: :get,
                      class: "btn outline-none " %>
      </div>


      <% if @product.image.attached? %>
        <%= image_tag url_for(@product.image), class: "card-img-top card-img-size border-0", alt: @product.name %>
      <% else %>
        <%= image_tag "grey-pant.webp", class: "card-img-top card-img-size", alt: "Description of the image" %>
      <% end %>
    </div>
    
    <%= render "product_details" %>

  </div>
</div>